# Generated by Django 2.2.5 on 2020-12-26 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kharg',
            name='date',
        ),
        migrations.AddField(
            model_name='kharg',
            name='tarikh',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 18, 58, 34, 844772)),
        ),
        migrations.AddField(
            model_name='kharg',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
