# Generated by Django 2.2.5 on 2020-12-26 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20201226_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kharg',
            name='tarikh',
        ),
        migrations.AddField(
            model_name='kharg',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 19, 2, 9, 640057)),
        ),
        migrations.CreateModel(
            name='Dakhl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 26, 19, 2, 9, 641057))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
